let csrf = ''; let models = []; const $ = id => document.getElementById(id); const json = async (url, options = {}) => { const r = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.detail || `HTTP ${r.status}`); return data; };
function showAdmin() { $('loginPanel').hidden = true; $('adminPanel').hidden = false; $('logout').hidden = false; loadModels(); }
async function loadModels() { try { const data = await json('/api/v1/admin/models'); models = data.items; $('modelRows').innerHTML = models.map(m => `<tr><td>${m.display_name}<br><small>${m.name}</small></td><td>${m.base_url || '--'}</td><td>${m.model_name || '--'}</td><td>${m.enabled ? '启用' : '停用'}<br><small>${m.last_status || ''}</small></td><td>${m.key_configured ? `已配置 ···${m.key_suffix}` : '未配置'}</td><td>${m.weight}</td><td><button data-edit="${m.id}">编辑</button> <button data-test="${m.id}">测试</button> <button data-delete="${m.id}">删除</button></td></tr>`).join(''); document.querySelectorAll('[data-edit]').forEach(b => b.onclick = () => editModel(Number(b.dataset.edit))); document.querySelectorAll('[data-test]').forEach(b => b.onclick = () => testModel(Number(b.dataset.test))); document.querySelectorAll('[data-delete]').forEach(b => b.onclick = () => deleteModel(Number(b.dataset.delete))); } catch (e) { if (e.message.includes('401')) location.reload(); else alert(e.message); } }
function editModel(id) { const m = models.find(item => item.id === id); $('editor').hidden = false; $('modelId').value = m?.id || ''; $('modelName').value = m?.name || ''; $('modelName').disabled = Boolean(m); $('displayName').value = m?.display_name || ''; $('baseUrl').value = m?.base_url || ''; $('apiKey').value = ''; $('modelNameValue').value = m?.model_name || ''; $('weight').value = m?.weight ?? 1; $('timeout').value = m?.timeout_seconds ?? 15; $('enabled').checked = Boolean(m?.enabled); $('formMessage').textContent = ''; }
async function testModel(id) { try { const data = await json(`/api/v1/admin/models/${id}/test`, { method: 'POST', headers: { 'X-CSRF-Token': csrf } }); alert(`测试成功，耗时 ${data.latency_ms} ms`); loadModels(); } catch (e) { alert(`测试失败：${e.message}`); } }
async function deleteModel(id) { if (!confirm('确认删除该模型配置？')) return; try { await json(`/api/v1/admin/models/${id}`, { method: 'DELETE', headers: { 'X-CSRF-Token': csrf } }); loadModels(); } catch (e) { alert(e.message); } }
$('loginForm').onsubmit = async e => { e.preventDefault(); try { const data = await json('/api/v1/admin/login', { method: 'POST', body: JSON.stringify({ username: $('username').value, password: $('password').value }) }); csrf = data.csrf_token; showAdmin(); } catch (e) { $('loginError').textContent = e.message; } };
$('modelForm').onsubmit = async e => { e.preventDefault(); const payload = { name: $('modelName').value, display_name: $('displayName').value, base_url: $('baseUrl').value, api_key: $('apiKey').value || null, model_name: $('modelNameValue').value, enabled: $('enabled').checked, weight: Number($('weight').value), timeout_seconds: Number($('timeout').value) }; try { const id = $('modelId').value; await json(id ? `/api/v1/admin/models/${id}` : '/api/v1/admin/models', { method: id ? 'PUT' : 'POST', headers: { 'X-CSRF-Token': csrf }, body: JSON.stringify(payload) }); $('editor').hidden = true; loadModels(); } catch (e) { $('formMessage').textContent = e.message; } };
$('newModel').onclick = () => editModel(null); $('cancelEdit').onclick = () => { $('editor').hidden = true; }; $('testModel').onclick = () => { const id = Number($('modelId').value); if (id) testModel(id); else $('formMessage').textContent = '请先保存模型配置'; }; $('logout').onclick = async () => { await json('/api/v1/admin/logout', { method: 'POST', headers: { 'X-CSRF-Token': csrf } }); location.reload(); };
